### ISSUE TITLE
Sync with the main nodecg repo

### ISSUE THREAD

**Issue by alvancamp** [nodecg/generator-nodecg#45]
(Originally was incorrectly posted to [generator-nodecg/#56](https://github.com/nodecg/nodecg-cli/issues/56))

nodecg-cli has been a bit unloved in the past year or two. It's not been kept up-to-date with changes happening in NodeCG itself. Specifically, it doesn't know about all the current package manifest properties, and it still recommends ~0.8.0 as the default compatibleRange.

This project should be given a once-over to ensure it is sync'd with NodeCG itself.

**Comment by Lange** [comment]
(This comment was also originally posted in the other, incorrect thread)

@Hoishin or @Seldszar, would either of you potentially be interested in working on this? I've been really happy with the work you've been doing on the main repo, and I'm very appreciative of the help.

**Comment by Hoishin** [comment]
OK now that it's on right place, yes, I am interested.

I have looked into the code before to see what can be done, but I don't have experience with yeoman generators. If @Seldszar is willing I don't mind, or could work on this together.

**Comment by Seldszar** [comment]
I don't mind either, we just need to know what to do and maybe split the
work to avoid conflicts.

2018-02-12 21:32 GMT+01:00 Keiichiro Amemiya <notifications@github.com>:

**Comment by Lange** [comment]
The first step would be to fully enumerate what properties of the `nodecg` stanza in `package.json` are not supported by `generator-nodecg`. From there, you could divide them up by importance and group them by functionality, and then decide how to divvy up the work.

**Comment by Lange** [comment]
That page might be missing some things. You may need to go through https://github.com/nodecg/nodecg/tree/master/lib/bundle-parser to fully discover all available parameters.

Some things probably don't belong in `generator-nodecg` though, like Sounds. Maybe someone has a convincing argument for those though.

**Comment by Lange** [comment]
I'm realizing that there's no one single canonical place where the schema of the `nodecg` stanza in `package.json` is defined. This is probably an indicator that NodeCG should have a clear schema for this file.

**Comment by Hoishin** [comment]
It would be nice to have JSON schema of `nodecg` stanza, that people can refer to, and that `nodecg/lib/bundle-parser` can use to validate `nodecg` stanza.

I'll probably end up with making similar thing in the process of reading through `nodecg/lib/bundle-parser`.

**Comment by Lange** [comment]
Agreed, it should be a JSON schema that is strictly enforced by NodeCG, so that we know it is the single source of truth. That makes writing docs and maintaining `generator-nodecg` much more straightforward.

**Comment by Hoishin** [comment]
Do you know if NodeCG refers to properties of the `nodecg` stanza outside of `bundle-parser` lib, whether directly or indirectly?

**Comment by Lange** [comment]
I don't think so -- `bundle-parser` should be the only thing reading the raw JSON. Everything after that should be reading the parsed objects created by `bundle-parser`.

**Comment by Lange** [comment]
But there could still be cases where like, an entire object is copied by `bundle-parser`, and then later on some other part of NodeCG is looking at that object's individual keys and values.

**Comment by Hoishin** [comment]
Yes that's what I'm concearning. For example `compatibleRange` is not referred in `bundle-parser` lib. It is required to grep the entire project with `bundle-parser` and see what keys are used.

**Comment by Hoishin** [comment]
Missing global props
- `enableCustomCues`: boolean
- `mount`: object, probably make another composer like graphic
- `assetCategories`: object, probably make another composer like graphic
- `soundCues`: object, probably make another composer like graphic (if we are making this)
- `bundleDependencies`: bundle name as key, semver as value

Missing in `dashboardPanels`
- `workspace`
- `fullbleed`: would require assertion to make sure only one fullbleed panel is assigned to each workspace (across the bundles, maybe)

That's what I can list after reading as much as I can. Some of the props are only referenced in HTML so... it would be hard to ensure everything has been checked.

Also JSON schema draft with just types: https://gist.github.com/Hoishin/9c04edffa3e17883c1fdc847eb9223db

**Comment by Lange** [comment]
- `enableCustomCues`: Oh wow, I completely forgot about this. I added this to accomodate a feature request that a specific client had, and I haven't used it since. I don't even fully remember what it does haha.
- `mount`: This _probably_ doesn't need to be one of the things that `generator-nodecg` prompts for. It's an advanced feature, and will likely just confuse users of `generator-nodecg`.
- `assetCategories`: This is tricky. I guess we can prompt for it? It's probably good to make users aware of the Assets feature in general.
- `soundCues`: Probably the same as `assetCategories`. If we're doing one, we should do both. But this seems unnecessary for someone just starting a bundle from nothing. Sound cues are generally added later in the development process. I want to avoid overwhelming people with options.
- `bundleDependencies`: Hm, this one is tricky too. I'd probably also classify this as an advanced feature and not something that should be prompted for, but I'd be open to thoughts on it.
- `workspace`: Yep, we should add this.
- `fullbleed`: This too.

That schema you linked looks like a great start. Here's some next steps:

- `dashboardPanels.width`: We can clamp this to the range that NodeCG supports, which I think is 1-8 but you might want to double-check.
- `dashboardPanels.headerColor`: We can the `pattern` property here to ensure that the provided values are valid hex colors: https://spacetelescope.github.io/understanding-json-schema/reference/regular_expressions.html
- `graphics.width`: Can have a `min` of `0`
- `graphics.height`: Can have a `min` of `0`
- `assetCategories.allowedTypes`: The `items` property should be defined here, to enforce a schema on the items within the array.
- `soundCues.defaultVolume`: Can be clamped to the range that NodeCG supports, which I think is 0-1
- `bundleDependencies`: Should have a `type` of `object`.

**Comment by Lange** [comment]
Adding advanced features to sub-generators only sounds good to me. :+1:
